services:
  whisper:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["${WHISPER_GPU_UUID}"]
              capabilities: [gpu]
