model_list:
  - model_name: default
    litellm_params:
      model: openai/default
      api_base: http://host.docker.internal:8080/api/v1
      api_key: lemonade

  - model_name: "*"
    litellm_params:
      model: openai/*
      api_base: http://host.docker.internal:8080/api/v1
      api_key: lemonade

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY

litellm_settings:
  drop_params: true
  set_verbose: false
