#!/bin/bash
# ============================================================================
# Dream Server macOS Installer -- Environment Generator
# ============================================================================
# Part of: installers/macos/lib/
# Purpose: Generate .env file, SearXNG config, OpenClaw configs
#          Uses /dev/urandom + openssl for secrets
#
# Canonical source: installers/phases/06-directories.sh (keep .env format in sync)
#
# Modder notes:
#   Modify generate_dream_env to add new environment variables.
#   All secrets use cryptographic RNG -- never use $RANDOM for secrets.
# ============================================================================

# Generate cryptographically secure hex string
new_secure_hex() {
    local bytes="${1:-32}"
    openssl rand -hex "$bytes" 2>/dev/null || \
        head -c "$bytes" /dev/urandom | xxd -p | tr -d '\n'
}

# Generate cryptographically secure base64 string
new_secure_base64() {
    local bytes="${1:-32}"
    openssl rand -base64 "$bytes" 2>/dev/null | tr -d '\n' || \
        head -c "$bytes" /dev/urandom | base64 | tr -d '\n'
}

# Detect system timezone (macOS-specific)
detect_timezone() {
    local tz=""
    # macOS: read from systemsetup or /etc/localtime symlink
    tz=$(systemsetup -gettimezone 2>/dev/null | awk -F': ' '{print $2}')
    if [[ -z "$tz" ]] && [[ -L /etc/localtime ]]; then
        tz=$(readlink /etc/localtime | sed 's|.*/zoneinfo/||')
    fi
    echo "${tz:-UTC}"
}

generate_dream_env() {
    local install_dir="$1"
    local tier="$2"

    # Generate secrets
    local webui_secret
    webui_secret=$(new_secure_hex 32)
    local n8n_pass
    n8n_pass=$(new_secure_base64 16)
    local litellm_key="sk-dream-$(new_secure_hex 16)"
    local livekit_secret
    livekit_secret=$(new_secure_base64 32)
    local livekit_api_key
    livekit_api_key=$(new_secure_hex 16)
    local dashboard_api_key
    dashboard_api_key=$(new_secure_hex 32)
    local openclaw_token
    openclaw_token=$(new_secure_hex 24)
    local opencode_password
    opencode_password=$(new_secure_base64 16)
    local searxng_secret
    searxng_secret=$(new_secure_hex 32)
    # macOS: llama-server runs natively, containers reach it via host.docker.internal
    local llm_api_url="http://host.docker.internal:8080"

    local tz
    tz=$(detect_timezone)
    local timestamp
    timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

    # Build .env content (matches Phase 06 format)
    cat > "${install_dir}/.env" << ENVEOF
# Dream Server Configuration -- ${TIER_NAME} Edition
# Generated by macOS installer v${DS_VERSION} on ${timestamp}
# Tier: ${tier} (${TIER_NAME})

#=== LLM Backend Mode ===
DREAM_MODE=local
LLM_API_URL=${llm_api_url}

#=== Cloud API Keys ===
ANTHROPIC_API_KEY=
OPENAI_API_KEY=
TOGETHER_API_KEY=

#=== LLM Settings (llama-server -- native Metal) ===
LLM_MODEL=${LLM_MODEL}
GGUF_FILE=${GGUF_FILE}
MAX_CONTEXT=${MAX_CONTEXT}
CTX_SIZE=${MAX_CONTEXT}
GPU_BACKEND=apple
HOST_RAM_GB=${SYSTEM_RAM_GB}

#=== Ports ===
OLLAMA_PORT=8080
WEBUI_PORT=3000
WHISPER_PORT=9000
TTS_PORT=8880
N8N_PORT=5678
QDRANT_PORT=6333
QDRANT_GRPC_PORT=6334
LITELLM_PORT=4000
OPENCLAW_PORT=7860
SEARXNG_PORT=8888

#=== Security (auto-generated, keep secret!) ===
WEBUI_SECRET=${webui_secret}
DASHBOARD_API_KEY=${dashboard_api_key}
N8N_USER=admin
N8N_PASS=${n8n_pass}
LITELLM_KEY=${litellm_key}
LIVEKIT_API_KEY=${livekit_api_key}
LIVEKIT_API_SECRET=${livekit_secret}
OPENCLAW_TOKEN=${openclaw_token}

#=== OpenCode Settings ===
OPENCODE_PORT=3003
OPENCODE_SERVER_PASSWORD=${opencode_password}

#=== Voice Settings ===
WHISPER_MODEL=base
TTS_VOICE=en_US-lessac-medium

#=== Web UI Settings ===
WEBUI_AUTH=true
ENABLE_WEB_SEARCH=true
WEB_SEARCH_ENGINE=searxng

#=== n8n Settings ===
N8N_AUTH=true
N8N_HOST=localhost
N8N_WEBHOOK_URL=http://localhost:5678
TIMEZONE=${tz}
ENVEOF

    # Restrict .env to current user only (chmod 600)
    chmod 600 "${install_dir}/.env" 2>/dev/null || true

    # Export secrets for use by other generators
    ENV_SEARXNG_SECRET="$searxng_secret"
    ENV_OPENCLAW_TOKEN="$openclaw_token"
    ENV_DASHBOARD_KEY="$dashboard_api_key"
}

generate_searxng_config() {
    local install_dir="$1"
    local secret_key="$2"

    local config_dir="${install_dir}/config/searxng"
    mkdir -p "$config_dir"

    cat > "${config_dir}/settings.yml" << SEARXEOF
use_default_settings: true
server:
  secret_key: "${secret_key}"
  bind_address: "0.0.0.0"
  port: 8080
  limiter: false
search:
  safe_search: 0
  formats:
    - html
    - json
engines:
  - name: duckduckgo
    disabled: false
  - name: google
    disabled: false
  - name: brave
    disabled: false
  - name: wikipedia
    disabled: false
  - name: github
    disabled: false
  - name: stackoverflow
    disabled: false
SEARXEOF
}

generate_openclaw_config() {
    local install_dir="$1"
    local llm_model="$2"
    local max_context="$3"
    local token="$4"
    local provider_url="${5:-http://host.docker.internal:8080}"
    local provider_name="local-llama"

    # Create directories
    local home_dir="${install_dir}/data/openclaw/home"
    local agent_dir="${home_dir}/agents/main/agent"
    local sess_dir="${home_dir}/agents/main/sessions"
    mkdir -p "$agent_dir" "$sess_dir"

    # Home config
    cat > "${home_dir}/openclaw.json" << OCEOF
{
  "models": {
    "providers": {
      "${provider_name}": {
        "baseUrl": "${provider_url}",
        "apiKey": "none",
        "api": "openai-completions",
        "models": [
          {
            "id": "${llm_model}",
            "name": "Dream Server LLM (Local)",
            "reasoning": false,
            "input": ["text"],
            "cost": {"input": 0, "output": 0, "cacheRead": 0, "cacheWrite": 0},
            "contextWindow": ${max_context},
            "maxTokens": 8192,
            "compat": {
              "supportsStore": false,
              "supportsDeveloperRole": false,
              "supportsReasoningEffort": false,
              "maxTokensField": "max_tokens"
            }
          }
        ]
      }
    }
  },
  "agents": {
    "defaults": {
      "model": {"primary": "${provider_name}/${llm_model}"},
      "models": {"${provider_name}/${llm_model}": {}},
      "compaction": {"mode": "safeguard"},
      "subagents": {"maxConcurrent": 20, "model": "${provider_name}/${llm_model}"}
    }
  },
  "commands": {"native": "auto", "nativeSkills": "auto"},
  "gateway": {
    "mode": "local",
    "bind": "lan",
    "controlUi": {"allowInsecureAuth": true},
    "auth": {"mode": "token", "token": "${token}"}
  }
}
OCEOF

    # Auth profiles
    cat > "${agent_dir}/auth-profiles.json" << AUTHEOF
{
  "version": 1,
  "profiles": {
    "${provider_name}:default": {
      "type": "api_key",
      "provider": "${provider_name}",
      "key": "none"
    }
  },
  "lastGood": {"${provider_name}": "${provider_name}:default"},
  "usageStats": {}
}
AUTHEOF

    # Models config
    cat > "${agent_dir}/models.json" << MODEOF
{
  "providers": {
    "${provider_name}": {
      "baseUrl": "${provider_url}",
      "apiKey": "none",
      "api": "openai-completions",
      "models": [
        {
          "id": "${llm_model}",
          "name": "Dream Server LLM (Local)",
          "reasoning": false,
          "input": ["text"],
          "cost": {"input": 0, "output": 0, "cacheRead": 0, "cacheWrite": 0},
          "contextWindow": ${max_context},
          "maxTokens": 8192,
          "compat": {
            "supportsStore": false,
            "supportsDeveloperRole": false,
            "supportsReasoningEffort": false,
            "maxTokensField": "max_tokens"
          }
        }
      ]
    }
  }
}
MODEOF

    # Workspace directory
    mkdir -p "${install_dir}/config/openclaw/workspace/memory"
}

# Auto-configure Perplexica to use local llama-server
configure_perplexica() {
    local perplexica_port="${1:-3004}"
    local llm_model="$2"
    local base_url="http://localhost:${perplexica_port}"

    # Check if Perplexica is responding
    local config_json
    config_json=$(curl -sf "${base_url}/api/config" 2>/dev/null) || return 1

    # Check if already configured
    if echo "$config_json" | python3 -c "import sys,json; d=json.load(sys.stdin); sys.exit(0 if d.get('values',{}).get('setupComplete') else 1)" 2>/dev/null; then
        return 0
    fi

    # Seed the chat model
    local providers
    providers=$(echo "$config_json" | python3 -c "
import sys, json
d = json.load(sys.stdin)
provs = d.get('values',{}).get('modelProviders',[])
openai_prov = next((p for p in provs if p.get('type') == 'openai'), None)
if not openai_prov:
    sys.exit(1)
openai_prov['chatModels'] = [{'key': '${llm_model}', 'name': '${llm_model}'}]
print(json.dumps(provs))
" 2>/dev/null) || return 1

    curl -sf -X POST "${base_url}/api/config" \
        -H "Content-Type: application/json" \
        -d "{\"key\":\"modelProviders\",\"value\":${providers}}" >/dev/null 2>&1 || true

    # Set default models
    local openai_id
    openai_id=$(echo "$config_json" | python3 -c "
import sys, json
d = json.load(sys.stdin)
provs = d.get('values',{}).get('modelProviders',[])
openai_prov = next((p for p in provs if p.get('type') == 'openai'), None)
transformers_prov = next((p for p in provs if p.get('type') == 'transformers'), None)
if not openai_prov:
    sys.exit(1)
emb_id = (transformers_prov or openai_prov).get('id', openai_prov['id'])
prefs = {
    'defaultChatProvider': openai_prov['id'],
    'defaultChatModel': '${llm_model}',
    'defaultEmbeddingProvider': emb_id,
    'defaultEmbeddingModel': 'Xenova/all-MiniLM-L6-v2'
}
print(json.dumps(prefs))
" 2>/dev/null) || return 1

    curl -sf -X POST "${base_url}/api/config" \
        -H "Content-Type: application/json" \
        -d "{\"key\":\"preferences\",\"value\":${openai_id}}" >/dev/null 2>&1 || true

    # Mark setup complete
    curl -sf -X POST "${base_url}/api/config" \
        -H "Content-Type: application/json" \
        -d '{"key":"setupComplete","value":true}' >/dev/null 2>&1 || true

    return 0
}
